version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=https://clubac-api-production.up.railway.app/api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
